#!/usr/bin/env python3
import sys
import gps
import psycopg2

pg_conn = psycopg2.connect(dbname="oceanos", user="oceanos")
pg_conn.autocommit = True

gps_client = gps.client.gpscommon(host="localhost")
try:
    gps_client.send(gps.client.gpsjson.generate_stream_command_new_style(
        gps.WATCH_ENABLE | gps.WATCH_JSON | gps.WATCH_DEVICE,
        sys.argv[1]))
except IndexError:
    sys.stderr.write("usage: %s gps_dev\n" % sys.argv[0])
    sys.exit(1)

cur = pg_conn.cursor()
while gps_client.read() != -1:
    cur.execute("INSERT INTO raw_gpsd_json (data) VALUES (%s)",
                (gps_client.response, ))
