#!/usr/bin/env python3
import sys
import socket
import struct
import psycopg2

pg_conn = psycopg2.connect(dbname="oceanos", user="oceanos")
pg_conn.autocommit = True

sock = socket.socket(socket.PF_CAN, socket.SOCK_RAW, socket.CAN_RAW)
try:
    sock.bind((sys.argv[1], ))
except IndexError:
    sys.stderr.write("usage: %s can_if\n" % sys.argv[0])
    sys.exit(1)

can_frame_t = struct.Struct("=IB3x8s")

cur = pg_conn.cursor()
buf = bytearray(can_frame_t.size)
while sock.recv_into(buf) != -1:
    can_id, can_dlc, data = can_frame_t.unpack_from(buf)
    cur.execute("INSERT INTO raw_can (id, data) VALUES (%s::bit(29), %s)",
                (can_id & socket.CAN_EFF_MASK, data[:can_dlc]))
